remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: "PHP Xmlify"
description: "PHP Xmlify is a PHP Xmlify template."
url: "https://norse-blue.github.io"
baseurl: "/php-xmlify/"
permalink: pretty
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "PHP Xmlify on GitHub":
    - "//github.com/norse-blue/php-skeleton"

# Google Analytics
ga_tracking:
